# Generated by Django 2.2.12 on 2021-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllCharts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puneet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=200)),
                ('executive_name', models.CharField(max_length=200, null=True)),
                ('rating', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
