# Generated by Django 2.2.12 on 2021-03-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllCharts', '0002_puneet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Puneet',
        ),
    ]
