# Generated by Django 3.1.7 on 2021-04-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoProvide', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='text_name',
        ),
        migrations.AddField(
            model_name='provider',
            name='category',
            field=models.CharField(choices=[('Alert', 'Alert'), ('Warning', 'Warning')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
