# Generated by Django 3.1.5 on 2021-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='executive_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='executive_level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_pass',
            field=models.CharField(max_length=32),
        ),
    ]
