# Generated by Django 3.1.5 on 2021-04-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210403_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='assigned',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='avg_res',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='avg_response',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='resolution',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='resolved',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='sla',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
