# Generated by Django 2.2.12 on 2021-04-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210403_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='ticket_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketinbox.Ticket', to_field='ticket_id'),
        ),
    ]
