# Generated by Django 2.2.12 on 2021-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210405_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executive',
            name='avg_res',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='executive_id',
        ),
        migrations.RemoveField(
            model_name='executive',
            name='resolution',
        ),
        migrations.AddField(
            model_name='executive',
            name='avg_resolution',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='executive',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='total_responses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='assigned',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='avg_response',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='resolved',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='sla',
            field=models.IntegerField(null=True),
        ),
    ]
