# Generated by Django 2.2.12 on 2021-04-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210405_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='id',
            field=models.AutoField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
