# Generated by Django 2.2.12 on 2021-04-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_executive_executive_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='assigned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='avg_resolution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='avg_response',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_dep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_pass',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='executive_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='resolved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='sla',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='total_responses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
