# Generated by Django 3.2 on 2021-04-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20210421_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='orderid',
            field=models.CharField(max_length=10),
        ),
    ]
