# Generated by Django 3.2.4 on 2021-06-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_auto_20210606_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
