# Generated by Django 3.1.5 on 2021-03-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=10, null=True)),
                ('assigned_to', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('ticket_type', models.CharField(max_length=200)),
                ('ticket_priority', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=30)),
                ('ticket_status', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(null=True)),
                ('due', models.DateTimeField(null=True)),
            ],
        ),
    ]
