# Generated by Django 3.1.5 on 2021-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketinbox', '0002_executive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Executive',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_dep',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
