# Generated by Django 3.1.5 on 2021-04-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketinbox', '0004_auto_20210402_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
