# Generated by Django 2.2.12 on 2021-04-05 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketinbox', '0006_auto_20210405_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 6, 1, 23, 790654), null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 5, 6, 1, 23, 790679), null=True),
        ),
    ]
