# Generated by Django 2.2.12 on 2021-04-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketinbox', '0009_auto_20210405_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
