# Generated by Django 2.2.12 on 2021-04-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_customer_no_of_order'),
        ('ticketinbox', '0010_auto_20210407_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Customer'),
        ),
    ]
