# Generated by Django 2.2.12 on 2021-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketinbox', '0012_auto_20210407_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Unassigned', 'Unassigned'), ('Unresolved', 'Unresolved'), ('Overdue', 'Overdue')], max_length=30),
        ),
    ]
