# Generated by Django 3.1.7 on 2021-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketinbox', '0018_auto_20210413_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='process',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
