# Generated by Django 3.2 on 2021-04-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketinbox', '0019_ticket_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='process',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20, null=True),
        ),
    ]
