# Generated by Django 3.1.5 on 2021-05-04 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketinbox', '0020_alter_ticket_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source', models.CharField(choices=[('Email', 'Email'), ('Web-form', 'Web-form'), ('Social-media', 'Social-media')], max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('Unassigned', 'Unassigned'), ('Unresolved', 'Unresolved'), ('Overdue', 'Overdue')], max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='process',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketinbox.source'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketinbox.priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketinbox.status'),
        ),
    ]
