# Generated by Django 2.2.12 on 2021-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('assigned', models.CharField(max_length=200)),
                ('resolved', models.CharField(max_length=200)),
                ('sla', models.CharField(max_length=200)),
                ('fcr', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=200)),
                ('res', models.CharField(max_length=200)),
                ('resolution', models.CharField(max_length=200)),
            ],
        ),
    ]
