# Generated by Django 3.1.7 on 2021-04-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reportsapp', '0003_puneet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Puneet',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
