# Generated by Django 3.1.5 on 2021-04-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_contact', models.IntegerField()),
                ('customer_address', models.CharField(max_length=300)),
                ('no_of_order', models.IntegerField()),
                ('nO_of_issues', models.IntegerField()),
            ],
        ),
    ]
