# Generated by Django 2.2.12 on 2021-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='issue',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
