# Generated by Django 2.2.12 on 2021-04-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210405_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='no_of_order',
        ),
    ]
